import Sidebar from "@/components/Sidebar";
import { Button } from "@/components/ui/button";
import { Post } from "@/utils/types";
import axios from "axios";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/navigation";
import Swal from 'sweetalert2';

type Props = {
  posts: Post[]
}

export async function getStaticProps() {
  try {
    const res = await fetch("http://127.0.0.1:8000/api/device");
    const posts = await res.json();
    console.log(posts);
    
    return {
      props: {
        posts,
      },
      revalidate: 60 * 60 * 24, // 24 hours
    };
  } catch (error) {
    console.error(error);
    return {
      props: {
        posts: [],
      },
    };
  }
}

export default function PostsListPage({posts}: Props) {
  const router = useRouter();


  // Delete function
  const handleDelete = async (id: string) => {
    try {
      const response = await axios.delete(
        `http://127.0.0.1:8000/api/device/${id}`
      );
      // window.alert('削除が完了しました。');
      Swal.fire({
        icon: 'success',
        title: '削除完了',
        text: '削除が完了しました。',
      });
      router.push('/posts')

    } catch (error) {
      console.error(error);
      alert("Error deleting post");
    }
  };


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='grid grid-cols-5'>
        <div className='col-span-1'> 
          <Sidebar />
        </div>

        <div className='col-span-4 p-5'>
          <div className="grid grid-cols-3">
            {posts.map((post) => (
           
              <div  key={post.id} onClick={() => router.push(`/posts/${post.id}`)} className="border p-4 my-4 mx-3 col-span-1 hover:shadow-xl bg-gray-100 hover:bg-gray-300 rounded-lg" >
                <p className="hover:text-blue-500">会社名: {post.company}</p>
                <p className="hover:text-blue-500">勤務地: {post.place}</p>
                <p className="hover:text-blue-500">応募状況: {post.status}</p>


                <a href={`/edit-post/${post.id}/`}>
                  <Button
                    className="hover:bg-gray-100 hover:text-black"
                  >
                    Edit
                  </Button>
                </a>
 
                <Button
                  className="hover:bg-gray-100 hover:text-black"
                  onClick={() => handleDelete(post.id)}
                >
                  Delete
                </Button>
              </div>
     
            ))}
          </div>
          </div>
      </div>

    </>
  )
}