import Sidebar from "@/components/Sidebar";
import { Button } from "@/components/ui/button";
import { Post } from "@/utils/types";
import axios from "axios";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import Swal from 'sweetalert2';

type Props = {
  data: Post[]
}


export async function getServerSideProps() {
  const url = `${process.env.NEXT_PUBLIC_API_URL}/device/`;
  try {
    const posts = await axios.get(url);
    return {
      props: {
        data: posts.data,
      },
    };
  } catch (error) {
    console.error(error);
    return {
      props: {
        data: [],
      },
    };
  }
}

export default function PostsListPage({data}: Props) {
  const router = useRouter();
  const [posts, setPosts] = useState<Post[]>(data);


  // Delete function
  const handleDelete = async (id: string) => {
    const url = `${process.env.NEXT_PUBLIC_API_URL}/device/${id}/`;
    try {
      await axios.delete(url);
      setPosts(posts.filter((post) => post.id !== id)); // リストを更新
      Swal.fire('削除完了', '削除が完了しました。', 'success');
      router.push('/posts');
    } catch (error) {
      console.error(error);
      Swal.fire('エラー', '削除に失敗しました。', 'error');
    }
  };


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='grid grid-cols-5'>
        <div className='col-span-1'> 
          <Sidebar />
        </div>

        <div className='col-span-4 p-5'>
          <div className="grid grid-cols-3">
            {posts.map((post) => (
           
              <div  key={post.id} onClick={() => router.push(`/posts/${post.id}`)} className="border p-4 my-4 mx-3 col-span-1 hover:shadow-xl bg-gray-100 hover:bg-gray-300 rounded-lg" >
                <p className="hover:text-blue-500">会社名: {post.company}</p>
                <p className="hover:text-blue-500">勤務地: {post.place}</p>
                <p className="hover:text-blue-500">応募状況: {post.status}</p>


                <a href={`/edit-post/${post.id}/`}>
                  <Button
                    className="hover:bg-gray-100 hover:text-black"
                  >
                    Edit
                  </Button>
                </a>
 
                <Button
                  className="hover:bg-gray-100 hover:text-black"
                  onClick={() => handleDelete(post.id)}
                >
                  Delete
                </Button>
              </div>
     
            ))}
          </div>
          </div>
      </div>

    </>
  )
}